#!/bin/sh
#
# chkconfig: 345 11 98
# description: bigserver

# Source function library.
. /etc/rc.d/init.d/functions

start()
{
    echo -n $"Starting bigserver: "
    /bin/sh /opt/bigops/bin/bigserver.sh start
}

stop()
{
    echo -n $"Shutting down bigserver: "
    /bin/sh /opt/bigops/bin/bigserver.sh stop
}

restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 2
	;;
esac

