#!/bin/sh
#
# chkconfig: 345 11 90
# description: bigserver

case "$1" in
  start)
        echo -n $"Starting bigserver: ......"
        /bin/sh /opt/bigops/bin/bigserver.sh start >/dev/null 2>&1
        echo
        ;;
  stop)
        echo -n $"Shutting down bigserver: ......"
        /bin/sh /opt/bigops/bin/bigserver.sh stop >/dev/null 2>&1
        echo
        ;;
  restart)
        cd "$CWD"
        $0 stop
        $0 start
        rc=$?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac

