#!/bin/sh
#
# chkconfig: 345 10 99
# description: bigweb

case "$1" in
  start)
        echo -n $"Starting bigweb: ......"
        /bin/sh /opt/bigops/bin/bigweb.sh start >/dev/null 2>&1
        echo
        ;;
  stop)
        echo -n $"Shutting down bigweb: ......"
        /bin/sh /opt/bigops/bin/bigweb.sh stop >/dev/null 2>&1
        echo
        ;;
  restart)
        cd "$CWD"
	$0 stop
	$0 start
	rc=$?
	;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac
 
