#!/bin/sh
#
# chkconfig: 345 10 98
# description: bigweb

# Source function library.
. /etc/rc.d/init.d/functions

start()
{
    echo -n $"Starting bigweb: start bigweb ......"
    /bin/sh /opt/bigops/bin/bigweb.sh start >/dev/null 2>&1
    echo
}

stop()
{
    echo -n $"Shutting down bigweb: stop bigweb ......"
    /bin/sh /opt/bigops/bin/bigweb.sh stop >/dev/null 2>&1
    echo
}

restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 2
	;;
esac

