#!/bin/sh
#chkconfig: 2345 81 05
#description: kibana
 
case "$1" in
start)
    cd  /opt/bigops/kibana
    ./bin/kibana --allow-root >/dev/null 2>&1 &
    echo "kibana startup"
    ;;  
stop)
    kibana_pid=`ps aux|grep node/bin/node|grep -v 'grep node/bin/node'| awk '{print $2}'`
    if [ ! -z "$kibana_pid" ];then
	    kill -9 $kibana_pid
    fi
    echo "kibana stopped"
    ;;  
restart)
    kibana_pid=`ps aux|grep node/bin/node|grep -v 'grep node/bin/node'| awk '{print $2}'`
    if [ ! -z "$kibana_pid" ];then
        kill -9 $kibana_pid
    fi
    echo "kibana stopped"

    cd  /opt/bigops/kibana
        ./bin/kibana --allow-root >/dev/null 2>&1 &
    echo "kibana startup"
    ;;  
*)
    echo "start|stop|restart"
    ;;  
esac

exit $?

